// Construction tasks: the `missing`/`no_access` rows of the coverage table, turned into work.
//
// Dry-run is the DEFAULT and `--apply` is the exception (R6): creating issues in repositories
// owned by other people is an outward-facing action, and a mistake there is not revertible by
// reverting a commit here. This module only produces the list; who opens the issues is a
// separate, explicit step.

export const TASK_KINDS = ['no_access', 'staging_missing', 'ci_missing', 'fix_missing', 'fix_upgrade', 'fix_unverified', 'check_missing', 'context_missing', 'ci_required_unknown'];

/** One task per real gap. Ordering is by repository so two runs produce the same list. */
export function buildConstructionTasks(rows) {
  const tasks = [];
  const add = (repo, kind, title, detail, refs) => tasks.push({ repo, kind, title, detail, refs });

  for (const r of rows) {
    if (r.read_state === 'no_access') {
      add(r.repo, 'no_access', `${r.repo}: not visible to the coverage reader`,
        (r.notes || []).join('; ') || 'repository could not be scanned',
        ['AC-40', 'AC-21']);
      continue;
    }
    if (r.read_state === 'empty') {
      add(r.repo, 'no_access', `${r.repo}: no tree on its default branch — nothing to cover yet`,
        'A repository with no commit has no workflows, no adapter and no profile. Onboard it after the first push; until then it is a known empty state, not a blind spot.',
        ['AC-40']);
      continue;
    }
    if (r.type && r.staging_required === true && !r.staging_present) {
      add(r.repo, 'staging_missing', `${r.repo}: staging is required but absent`,
        'Owner rule 2026-09-16 blocks the merge until staging is green. Add a staging job, or set staging.required=false in .devbaseline.json with a reason.',
        ['AC-20', 'AC-21']);
    }
    if (r.ci_present === false) {
      add(r.repo, 'ci_missing', `${r.repo}: no CI workflow`,
        'Copy .github/workflows/ci.yml from the devbaseline reusable workflow (mode=ci) or pin the repository baseline.',
        ['AC-20', 'AC-21']);
    }
    if (r.fix && r.fix.supported && r.fix.fixer_present === false) {
      add(r.repo, 'fix_missing', 'fix_upgrade', 'fix_unverified', `${r.repo}: AutoFix callable is declared but not installed`,
        `Install ${r.fix.autofix_callable}@${r.autofix_ref || 'the pinned ref'} via the setup procedure (setup → run → evidence → teardown).`,
        ['AC-21', 'AC-44']);
    }
    if (r.fix?.supported && r.fix.fixer_present !== false) {
      const refs = r.fix.observed_refs || [];
      if (refs.some(ref => ref !== r.fix.desired_ref)) {
        add(r.repo, 'fix_upgrade', `${r.repo}: review existing AutoFix pins`,
          `Observed refs: ${refs.join(', ')}; desired ref: ${r.fix.desired_ref}. Compare releases and upgrade through setup; installation is already present.`, ['AC-21', 'AC-44']);
      } else if (r.fix.installation === 'remote_caller' || r.fix.installation === 'unknown' || r.fix.evidence_complete === false) {
        add(r.repo, 'fix_unverified', `${r.repo}: verify AutoFix installation evidence`,
          `Installation: ${r.fix.installation}; observed refs: ${refs.join(', ') || 'unknown'}. Obtain successful run evidence; presence alone is not proof of working integration.`, ['AC-21', 'AC-44']);
      }
    }
    if (r.profile === 'minimal') {
      add(r.repo, 'check_missing', `${r.repo}: no check entrypoint — check is a no-op marked missing`,
        'Add package.json / pyproject.toml / a documented entrypoint, or pin the check command in .devbaseline.json.',
        ['AC-40']);
    }
    if (r.ci_required === null) {
      add(r.repo, 'ci_required_unknown', `${r.repo}: required checks are unknown`,
        'Inventory records presence, never "this job is required". Record the branch protection required checks here so the coverage table can show both halves.',
        ['AC-20', 'AC-40']);
    }
    if (!r.context?.entrypoints_present?.length) {
      add(r.repo, 'context_missing', `${r.repo}: no context entrypoints resolve`,
        'Pin context.entrypoints in .devbaseline.json so the context builder has a root.',
        ['AC-42']);
    }
  }
  tasks.sort((a, b) => a.repo.localeCompare(b.repo) || a.kind.localeCompare(b.kind));
  return tasks;
}

export function renderConstructionTasksMd({ tasks, profileRef, applied = false }) {
  const byRepo = new Map();
  for (const t of tasks) {
    if (!byRepo.has(t.repo)) byRepo.set(t.repo, []);
    byRepo.get(t.repo).push(t);
  }
  const lines = [
    '<!-- GENERATED by `node scripts/devbaseline.mjs inventory` (Z01). Do not edit by hand. -->',
    '',
    '# Construction tasks',
    '',
    `Derived from the coverage table built by pr-autofix \`${profileRef}\` · ${tasks.length} task(s) · dry-run: ${applied ? 'APPLIED' : 'yes, no issue was created'}.`,
    '',
    'Each task below is a gap in the baseline — a missing method, not a missing nicety. Owner and',
    'card go in when the list is applied; until then nobody has been notified by this file.',
    '',
  ];
  if (!tasks.length) {
    lines.push('No gaps found: every listed repository has a check, a fixer, CI, staging coverage and resolvable context entrypoints.');
    return `${lines.join('\n')}\n`;
  }
  for (const [repo, list] of byRepo) {
    lines.push(`## ${repo}`, '');
    for (const t of list) {
      lines.push(`- **${t.title}**`);
      lines.push(`  - kind: \`${t.kind}\``);
      lines.push(`  - ${t.detail}`);
      lines.push(`  - acceptance: ${t.refs.join(', ')}`);
    }
    lines.push('');
  }
  return `${lines.join('\n')}\n`;
}