// Inventory: the coverage table (AC-40).
//
// One row per participating repository, every column always present. `*_present` and
// `*_required` are SEPARATE columns on purpose: collapsing them turns "a job named staging
// exists" into "staging is green", which is the specific lie the owner rule (2026-09-16)
// exists to prevent. A column that is unknown is `null`, never `false`.
//
// The repository list is an INPUT (inventory/repos.json), not a discovery scan: a table that
// silently enumerated every repository in the organisation could not be checked by acceptance.
//
// ── One derivation, two sources ─────────────────────────────────────────────────
// `scanSource` is the ONLY place a row is built. It talks to a repository exclusively through a
// source (source.mjs), so the local checkout and the live GitHub API produce columns from the
// same code and cannot disagree. The earlier shape — `scanLocal` filling 18 columns and
// `scanRemote` filling 5 — is what made the live table empty and made pr-autofix report
// `staging_present: no` for itself while its own staging-gate job was green.

import fs from 'node:fs';
import path from 'node:path';
import { parseAdapterText, effectiveConfig } from './adapter.mjs';
import { profileHasBuild, listProfileIds } from './profile.mjs';
import { resolveRepo, resolveFixInstallation } from './resolve.mjs';
import { toolVersion, TOOL_NAME } from './log.mjs';
import { findSecretValues } from './secrets.mjs';
import { localSource, liveSource, workflowFiles } from './source.mjs';

export const COVERAGE_COLUMNS = [
  'repo', 'owner', 'type', 'profile', 'profile_ref', 'adapter', 'build', 'check', 'fix', 'verify',
  'context', 'logs', 'ci_present', 'ci_required', 'staging_present', 'staging_required',
  'autofix_ref', 'read_state', 'notes',
];

// `read_state` replaces the old boolean `readable` (R8). One boolean could not say WHICH blind
// spot a row was in, so the table could not be regenerated by a second equally-authorized reader:
// GitHub answers 404 both for "no such repository" and "this token may not read it", and the two
// need different work. `read` — every column below was actually read.
// `empty`     — the repository answered but has no tree on its default branch (no commit yet).
// `no_access` — THIS reader cannot see it; its other columns are unknown, not false.
export const READ_STATES = ['read', 'empty', 'no_access'];

export const isReadable = (row) => row.read_state === 'read' || row.read_state === 'empty';

const EMPTY = (repo, owner) => ({
  repo, owner, type: null, profile: null, profile_ref: toolVersion(), adapter: null, build: null,
  check: null, fix: null, verify: null, context: null, logs: null,
  ci_present: false, ci_required: null, staging_present: false, staging_required: null,
  autofix_ref: null, read_state: 'no_access', notes: [],
});



// ── Staging detection: one definition, both paths ──────────────────────────────
// A staging job is a JOB whose id/name mentions staging. A workflow FILE whose name mentions
// staging is not one: in this very repository the `staging-gate` job lives inside ci.yml (proof:
// CI run on merge-commit 335e7601, job staging-gate = success), so name-only detection wrote
// `staging_present: no` for the one repository that certainly has staging — a false construction
// task and a false merge blocker under R7.
const STAGING_JOB_RE = /^\s{0,4}(?:staging|stage|deploy-staging)[\w-]*\s*:/m;
const STAGING_GATE_RE = /\bstaging[-_]?gate\b/i;

function textHasStagingJob(text) {
  return STAGING_JOB_RE.test(text) || STAGING_GATE_RE.test(text);
}

/** @param {{readText: (rel: string) => Promise<string|null>, files: Set<string>}} source */
async function hasStagingJob(source) {
  for (const f of workflowFiles(source)) {
    const text = await source.readText(f);
    if (text !== null && textHasStagingJob(text)) return true;
  }
  return false;
}

/**
 * Build one row from any source. `adapterRaw` is the adapter text (or null when absent).
 * @param {{repo: string, owner: string, type_hint?: string|null, ci_required?: boolean|null,
 *          note?: string}} entry
 * @param {{kind: string, origin: string, readable: boolean, files: Set<string>,
 *          has: (rel: string) => boolean, readText: (rel: string) => Promise<string|null>}} source
 */
export async function scanSource(entry, source, profileRef = toolVersion()) {
  const repo = entry.repo;
  const owner = repo.includes('/') ? repo.split('/')[0] : '';
  const notes = [];

  if (!source.readable) {
    const row = EMPTY(repo, owner);
    row.notes = [`no_access: ${source.kind === 'local' ? `local path does not exist` : `repository is not visible to this reader`} (${entry.path || source.origin})`];
    return row;
  }

  // The adapter is read through the source, so the live path validates the same file the local
  // path does instead of silently assuming "no adapter".
  const adapterRaw = await source.readText('.devbaseline.json');
  const adapterResult = parseAdapterText(adapterRaw);
  if (!adapterResult.ok) {
    const row = EMPTY(repo, owner);
    row.notes = [`${adapterResult.rule_id}: ${adapterResult.message}`];
    return row;
  }
  // One seam with validate/verify (R5). The adapter is read through the SOURCE (local path or the
  // GitHub API), so what was read is passed in rather than re-read from disk — two reads would be
  // two answers to "what did this repository pin".
  const prof = resolveRepo({ repoDir: '.', exists: source.has, typeHint: entry.type_hint || null, adapter: adapterResult });
  if (!prof.ok) {
    const row = EMPTY(repo, owner);
    row.notes = [`${prof.rule_id}: ${prof.message}`];
    return row;
  }

  const profile = prof.profile;
  const config = effectiveConfig({ profile, adapter: adapterResult.adapter });
  const callableRel = config.fix_autofix_callable;
  const fixInstallation = await resolveFixInstallation(source, callableRel, config.fix_ref || (callableRel ? profileRef : null));
  const entrypointsPresent = config.context_entrypoints.filter(e => source.has(e));
  const wfFiles = workflowFiles(source);

  const ciPresent = wfFiles.length > 0;
  const stagingPresent = (await hasStagingJob(source)) || Boolean(config.staging_command);
  const docsOnly = profile.repo_type === 'docs';
  const stagingRequired = docsOnly ? false : config.staging_required;
  if (docsOnly) notes.push('staging_required=false: docs_only');
  if (profile.id === 'minimal') notes.push('check: missing — no recognised entrypoint (profile minimal)');
  if (callableRel && fixInstallation.fixer_present === false) notes.push(`fix: missing — repository has no ${callableRel}`);
  if (!callableRel) notes.push(`fix: unsupported_by_profile (profile ${profile.id} declares no fixer)`);
  if (stagingRequired && !stagingPresent) notes.push('staging: missing — required but absent');
  if (!ciPresent) notes.push('ci: missing — no workflow in .github/workflows');
  if (adapterResult.adapter === null) notes.push(`adapter: derived (${prof.derivation})`);
  if (source.kind === 'live') {
    // No counters here. `files=N, workflows=M` are properties of the CURRENT commit, not of the
    // repository's coverage: with them in the compared artifact the byte-exact drift gate turned
    // red on every unrelated commit in every participating repository — including this one's own
    // inventory PR — so the gate would have been disabled by the first team that touched anything.
    // The structural facts a reviewer acts on are already columns (`ci_present`, `staging_present`,
    // `fix.fixer_present`, `context.entrypoints_present`); a truncation is kept because it means
    // those columns are partial and must be looked at.
    notes.push(`live: tree read from ${source.defaultBranch}${source.truncated ? ', tree TRUNCATED by GitHub — file list is partial' : ''}${source.empty ? ', repository has no tree on its default branch' : ''}`);
  }
  if (entry.note) notes.push(`scope: ${entry.note}`);

  return {
    repo,
    owner,
    type: entry.type_hint || profile.repo_type,
    profile: profile.id,
    profile_ref: profileRef,
    adapter: adapterResult.adapter === null ? 'derived' : 'file',
    build: profileHasBuild(profile),
    check: config.check_commands,
    fix: { autofix_callable: callableRel, ...fixInstallation, cap: config.fix_cap, supported: Boolean(callableRel) },
    verify: config.verify_commands,
    context: { builder: profile.context.builder, entrypoints_present: entrypointsPresent },
    logs: { contract_version: profile.logs.contract_version, retention_days: config.logs.retention_days },
    ci_present: ciPresent,
    ci_required: typeof entry.ci_required === 'boolean' ? entry.ci_required : null,
    staging_present: stagingPresent,
    staging_required: stagingRequired,
    autofix_ref: fixInstallation.desired_ref,
    read_state: source.empty ? 'empty' : 'read',
    notes,
  };
}

/** Local checkout path (kept as a named export: the sandbox and callers address it directly). */
export async function scanLocal(entry, profileRef = toolVersion()) {
  return scanSource(entry, localSource(entry.path), profileRef);
}

/** Live path. Requires GH_TOKEN; without it the row says so instead of guessing. */
async function scanRemote(entry, profileRef = toolVersion()) {
  const repo = entry.repo;
  const parts = repo.split('/').filter(Boolean);
  const owner = parts.length ? parts[0] : '';
  if (parts.length !== 2) {
    // Say what is wrong with the INPUT instead of asking the API about a name we invented.
    // `owner/extra/name` used to be silently truncated to `owner/name` and came back as
    // `no_access: HTTP 404` — a fact about the API, offered as an answer about the repository.
    const row = EMPTY(repo, owner);
    row.notes = [`input_invalid: repository id must be "owner/name" (got "${repo}"); supply \`path\` for a local checkout`];
    return row;
  }
  if (!process.env.GH_TOKEN) {
    const row = EMPTY(repo, owner);
    row.notes = ['no_access: no local path and no GH_TOKEN — supply `path` (offline) or GH_TOKEN (live)'];
    return row;
  }
  const name = parts[1];
  try {
    const source = await liveSource({ owner, name });
    return await scanSource(entry, source, profileRef);
  } catch (e) {
    const row = EMPTY(repo, owner);
    row.notes = [`no_access: GitHub API ${e.message}`];
    return row;
  }
}

/** @returns {Promise<{rows: object[], unreadable: number}>} */
export async function buildCoverage(entries, { profileRef = toolVersion() } = {}) {
  const rows = [];
  for (const e of entries) {
    rows.push(e.path ? await scanLocal(e, profileRef) : await scanRemote(e, profileRef));
  }
  rows.sort((a, b) => a.repo.localeCompare(b.repo));
  return { rows, unreadable: rows.filter(r => !isReadable(r)).length };
}

/**
 * The part of a row a drift gate may compare.
 *
 * A row the reader could not see has no other columns to compare — they are UNKNOWN, and
 * inventing them is the lie the whole table exists to prevent. So a `no_access` row contributes
 * only its identity and its state: the gate still fails when a repository becomes visible or
 * invisible (that is exactly the moment the table must be regenerated), and it does not fail on
 * content it was never able to read. Everything else is compared in full.
 */
export function stableRow(row) {
  if (isReadable(row)) return row;
  return { repo: row.repo, read_state: row.read_state };
}

export function stableRows(rows) {
  return rows.map(stableRow);
}

export function renderStableJson({ rows, profileRef, unreadable }) {
  return `${JSON.stringify({
    generated_by: `${TOOL_NAME} ${profileRef}`,
    columns: COVERAGE_COLUMNS,
    compared: 'stableRow — a no_access row is compared by (repo, read_state) only',
    repos: stableRows(rows),
  }, null, 2)}\n`;
}

export function renderCoverageMd({ rows, profileRef, unreadable }) {
  const head = [
    '<!-- GENERATED by `node scripts/devbaseline.mjs inventory` (Z01). Do not edit by hand. -->',
    '',
    '# Repository coverage',
    '',
    `Built by pr-autofix \`${profileRef}\` · ${rows.length} repositories · ${unreadable} not visible to this reader.`,
    '',
    '`*_present` is what exists. `*_required` is what the merge rule demands. They are',
    'deliberately different columns: presence of a job is not a green job.',
    '',
    '`read_state` is `read` (every column was read), `empty` (the repository has no tree on its',
    'default branch yet) or `no_access` (this reader cannot see it — the other columns are',
    'unknown, not false). A `no_access` row is a construction task, never a silent zero.',
    '',
    `Profiles shipped: ${listProfileIds().join(', ')}. Credentials appear as NAMES only.`,
    '',
  ].join('\n');
  const table = [
    `| ${COVERAGE_COLUMNS.join(' | ')} |`,
    `|${COVERAGE_COLUMNS.map(() => '---').join('|')}|`,
    ...rows.map(r => `| ${COVERAGE_COLUMNS.map(c => cell(r, c)).join(' | ')} |`),
    '',
  ].join('\n');
  return `${head}${table}`;
}

function cell(row, col) {
  const v = row[col];
  if (v === null || v === undefined) return '—';
  if (typeof v === 'boolean') return v ? 'yes' : 'no';
  if (Array.isArray(v)) return v.length ? `\`${v.join(' ')}\`` : '—';
  if (typeof v === 'object') return `\`${JSON.stringify(v).replace(/\|/g, '\\|')}\``;
  return String(v).replace(/\|/g, '\\|');
}

/** Guard before anything is written: no credential value may leave the process (AC-07). */
export function assertNoSecretValues(rows) {
  const hits = rows.flatMap(r => findSecretValues(r, r.repo));
  if (!hits.length) return null;
  return hits[0];
}
